// GENERATED by scripts/gen-registry.js from contract/operations.json. Do not edit.
export const CONTRACT_VERSION = 1;
export const PAGE_SIZE = 50;
export type PathParamType = 'CODE' | 'DOCKEY' | 'AUTOKEY' | null;
export type OpName = 'list' | 'get' | 'create' | 'update' | 'delete';
export type ResourceKind = 'master' | 'transactional' | 'report';
export interface RegistryEntry {
	resource: string; name: string; pathParam: PathParamType; kind: ResourceKind;
	group: string | null; ops: OpName[]; verifyGet: boolean; verifyEndpoint: boolean;
}
export const REGISTRY: RegistryEntry[] = [
	{
		"resource": "account",
		"name": "Account",
		"pathParam": "CODE",
		"kind": "master",
		"group": null,
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "agent",
		"name": "Agent",
		"pathParam": "CODE",
		"kind": "master",
		"group": null,
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "area",
		"name": "Area",
		"pathParam": "CODE",
		"kind": "master",
		"group": null,
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "assetdisposal",
		"name": "Asset Disposal",
		"pathParam": "AUTOKEY",
		"kind": "master",
		"group": null,
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "assetgroup",
		"name": "Asset Group",
		"pathParam": "AUTOKEY",
		"kind": "master",
		"group": null,
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "assetitem",
		"name": "Asset Item",
		"pathParam": "AUTOKEY",
		"kind": "master",
		"group": null,
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "batch",
		"name": "Stock Batch",
		"pathParam": "AUTOKEY",
		"kind": "master",
		"group": null,
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "companycategory",
		"name": "Company Category",
		"pathParam": "CODE",
		"kind": "master",
		"group": null,
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": true,
		"verifyEndpoint": false
	},
	{
		"resource": "currency",
		"name": "Currency",
		"pathParam": "CODE",
		"kind": "master",
		"group": null,
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "itemtemplate",
		"name": "Item Template",
		"pathParam": "CODE",
		"kind": "master",
		"group": null,
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "location",
		"name": "Location",
		"pathParam": "CODE",
		"kind": "master",
		"group": null,
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "memberpoint",
		"name": "Member Point",
		"pathParam": "DOCKEY",
		"kind": "master",
		"group": null,
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "pmmethod",
		"name": "Payment Method",
		"pathParam": "CODE",
		"kind": "master",
		"group": null,
		"ops": [
			"list",
			"get",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "pricetag",
		"name": "Price Tag",
		"pathParam": "CODE",
		"kind": "master",
		"group": null,
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "project",
		"name": "Project",
		"pathParam": "CODE",
		"kind": "master",
		"group": null,
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "shipper",
		"name": "Shipper",
		"pathParam": "AUTOKEY",
		"kind": "master",
		"group": null,
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "stockcategory",
		"name": "Stock Category",
		"pathParam": "CODE",
		"kind": "master",
		"group": null,
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": true,
		"verifyEndpoint": false
	},
	{
		"resource": "stockgroup",
		"name": "Stock Group",
		"pathParam": "CODE",
		"kind": "master",
		"group": null,
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": true,
		"verifyEndpoint": false
	},
	{
		"resource": "tariff",
		"name": "Tariff",
		"pathParam": "AUTOKEY",
		"kind": "master",
		"group": null,
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": true,
		"verifyEndpoint": false
	},
	{
		"resource": "tax",
		"name": "Tax",
		"pathParam": "AUTOKEY",
		"kind": "master",
		"group": null,
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": true,
		"verifyEndpoint": false
	},
	{
		"resource": "terms",
		"name": "Terms",
		"pathParam": "CODE",
		"kind": "master",
		"group": null,
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "whtax",
		"name": "Withholding Tax",
		"pathParam": "AUTOKEY",
		"kind": "master",
		"group": null,
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": true,
		"verifyEndpoint": false
	},
	{
		"resource": "customer",
		"name": "Customer",
		"pathParam": "CODE",
		"kind": "master",
		"group": null,
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "supplier",
		"name": "Supplier",
		"pathParam": "CODE",
		"kind": "master",
		"group": null,
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "stockitem",
		"name": "Stock Item",
		"pathParam": "DOCKEY",
		"kind": "master",
		"group": null,
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "salesinvoice",
		"name": "Sales Invoice",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "sales",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "salesorder",
		"name": "Sales Order",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "sales",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "salesquotation",
		"name": "Sales Quotation",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "sales",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "salescreditnote",
		"name": "Sales Credit Note",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "sales",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "salesdebitnote",
		"name": "Sales Debit Note",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "sales",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "salescancellednote",
		"name": "Sales Cancelled Note",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "sales",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "cashsales",
		"name": "Cash Sales",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "sales",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "deliveryorder",
		"name": "Delivery Order",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "sales",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "extradeliveryorder",
		"name": "Extra Delivery Order",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "sales",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "purchaseinvoice",
		"name": "Purchase Invoice",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "purchase",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "purchaseorder",
		"name": "Purchase Order",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "purchase",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "purchaserequest",
		"name": "Purchase Request",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "purchase",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "purchasereturned",
		"name": "Purchase Return",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "purchase",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "purchasedebitnote",
		"name": "Purchase Debit Note",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "purchase",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "purchasecancellednote",
		"name": "Purchase Cancelled Note",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "purchase",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "cashpurchase",
		"name": "Cash Purchase",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "purchase",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "goodsreceived",
		"name": "Goods Received",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "purchase",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "extragoodsreceived",
		"name": "Extra Goods Received",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "purchase",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "customerinvoice",
		"name": "Customer Invoice",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "ar",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": true
	},
	{
		"resource": "customercreditnote",
		"name": "Customer Credit Note",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "ar",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "customerdebitnote",
		"name": "Customer Debit Note",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "ar",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "customerpayment",
		"name": "Customer Payment",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "ar",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "customerdeposit",
		"name": "Customer Deposit",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "ar",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "customerrefund",
		"name": "Customer Refund",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "ar",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "customercontra",
		"name": "Customer Contra",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "ar",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "supplierinvoice",
		"name": "Supplier Invoice",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "ap",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "suppliercreditnote",
		"name": "Supplier Credit Note",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "ap",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "supplierdebitnote",
		"name": "Supplier Debit Note",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "ap",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "supplierpayment",
		"name": "Supplier Payment",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "ap",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "supplierdeposit",
		"name": "Supplier Deposit",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "ap",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "supplierrefund",
		"name": "Supplier Refund",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "ap",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "suppliercontra",
		"name": "Supplier Contra",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "ap",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "journalentry",
		"name": "Journal Entry",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "gl",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "paymentvoucher",
		"name": "Payment Voucher",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "gl",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "receiptvoucher",
		"name": "Receipt Voucher",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "gl",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "bankadjustment",
		"name": "Bank Adjustment",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "gl",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "stockadjustment",
		"name": "Stock Adjustment",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "stock",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "stockissue",
		"name": "Stock Issue",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "stock",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "stockreceived",
		"name": "Stock Received",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "stock",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "stocktransfer",
		"name": "Stock Transfer",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "stock",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "assembly",
		"name": "Assembly",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "stock",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "disassembly",
		"name": "Disassembly",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "stock",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "joborder",
		"name": "Job Order",
		"pathParam": "DOCKEY",
		"kind": "transactional",
		"group": "stock",
		"ops": [
			"list",
			"get",
			"create",
			"update",
			"delete"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "profile",
		"name": "Company Profile",
		"pathParam": null,
		"kind": "report",
		"group": null,
		"ops": [
			"get"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "version",
		"name": "App Version",
		"pathParam": null,
		"kind": "report",
		"group": null,
		"ops": [
			"get"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "stockaging",
		"name": "Stock Aging",
		"pathParam": null,
		"kind": "report",
		"group": null,
		"ops": [
			"get"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "stockanalysis",
		"name": "Stock Analysis",
		"pathParam": null,
		"kind": "report",
		"group": null,
		"ops": [
			"get"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "stockbalanceinquiry",
		"name": "Stock Balance Inquiry",
		"pathParam": null,
		"kind": "report",
		"group": null,
		"ops": [
			"get"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "stockbatchexpiry",
		"name": "Stock Batch Expiry",
		"pathParam": null,
		"kind": "report",
		"group": null,
		"ops": [
			"get"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "stockcard",
		"name": "Stock Card",
		"pathParam": null,
		"kind": "report",
		"group": null,
		"ops": [
			"get"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "stockcardqty",
		"name": "Stock Card Qty",
		"pathParam": null,
		"kind": "report",
		"group": null,
		"ops": [
			"get"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "stockmonthendbalance",
		"name": "Stock Month End Balance",
		"pathParam": null,
		"kind": "report",
		"group": null,
		"ops": [
			"get"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "stockphysicalworksheet",
		"name": "Stock Physical Worksheet",
		"pathParam": null,
		"kind": "report",
		"group": null,
		"ops": [
			"get"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "stockreorderadvice",
		"name": "Stock Reorder Advice",
		"pathParam": null,
		"kind": "report",
		"group": null,
		"ops": [
			"get"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "stockserialnumberconflict",
		"name": "Stock Serial No Conflict",
		"pathParam": null,
		"kind": "report",
		"group": null,
		"ops": [
			"get"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	},
	{
		"resource": "stockserialnumberoutstanding",
		"name": "Stock Serial No Outstanding",
		"pathParam": null,
		"kind": "report",
		"group": null,
		"ops": [
			"get"
		],
		"verifyGet": false,
		"verifyEndpoint": false
	}
];
